"""add_json_fields_to_models

Revision ID: 981f2857c0f7
Revises: d393a04b0eef
Create Date: 2025-09-13 13:04:02.693786

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '981f2857c0f7'
down_revision = 'd393a04b0eef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ai_analyses', sa.Column('analysis_data', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    op.add_column('device_calibrations', sa.Column('calibration_data', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    op.add_column('skiing_sessions', sa.Column('session_metadata', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    op.add_column('user_sessions', sa.Column('device_info', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_sessions', 'device_info')
    op.drop_column('skiing_sessions', 'session_metadata')
    op.drop_column('device_calibrations', 'calibration_data')
    op.drop_column('ai_analyses', 'analysis_data')
    # ### end Alembic commands ###
