"""Add barometer_data table

Revision ID: a1b2c3d4e5f6
Revises: d393a04b0eef
Create Date: 2025-01-27 10:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'a1b2c3d4e5f6'
down_revision = 'd393a04b0eef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('barometer_data',
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('pressure', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('temperature', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('error_code', sa.Integer(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('device_id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['skiing_sessions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_barometer_data_device_id'), 'barometer_data', ['device_id'], unique=False)
    op.create_index(op.f('ix_barometer_data_session_id'), 'barometer_data', ['session_id'], unique=False)
    op.create_index(op.f('ix_barometer_data_user_id'), 'barometer_data', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_barometer_data_user_id'), table_name='barometer_data')
    op.drop_index(op.f('ix_barometer_data_session_id'), table_name='barometer_data')
    op.drop_index(op.f('ix_barometer_data_device_id'), table_name='barometer_data')
    op.drop_table('barometer_data')
    # ### end Alembic commands ###

