"""update model related calibration and metrics

Revision ID: b1fbdc302586
Revises: c123456789ab
Create Date: 2025-11-16 20:24:26.536050

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'b1fbdc302586'
down_revision = 'c123456789ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('device_calibration_samples_calibration_id_fkey', 'device_calibration_samples', type_='foreignkey')
    op.create_foreign_key(None, 'device_calibration_samples', 'device_calibrations', ['calibration_id'], ['id'])
    op.alter_column('device_calibrations', 'failure_reason',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('device_calibrations', 'failure_reason',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_constraint(None, 'device_calibration_samples', type_='foreignkey')
    op.create_foreign_key('device_calibration_samples_calibration_id_fkey', 'device_calibration_samples', 'device_calibrations', ['calibration_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
