"""remove error_code in barometer

Revision ID: cc9d2e67ab33
Revises: 96e444f6b932
Create Date: 2025-11-08 12:41:10.055158

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'cc9d2e67ab33'
down_revision = '96e444f6b932'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('barometer_data', 'error_code')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('barometer_data', sa.Column('error_code', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
